### PR TITLE
[memory][fs-storage] Fix link deletion and empty link content handling

### LINKED ISSUE #193: Invalid sc-link deletion
**Describe the bug**
After removing sc-link with content and searching links with similar content system returns sc-link with empty content

**To Reproduce**
1. Create link with content
2. Remove it with context's method "EraseElement"
3. Create link with similar content
4. Start search of links by them content

**Expected behavior**
I expected the returned vector of sc-links to be empty. 

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Version [0.7.0]

### PR DESCRIPTION
**Pull request by NikitaZotov**
* [x] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)
* [x] Update changelog

Fix #193.

### CODE REVIEW

File: sc-memory/tests/sc-memory/common/sc-link.cpp [hunk 1]
```diff
@@ -365,3 +365,20 @@ TEST_F(ScLinkTest, find_strings_by_substr_as_prefix)
...
+  EXPECT_TRUE(linkAddr1.IsValid());
+
+  EXPECT_TRUE(ctx.SetLinkContent(linkAddr1, "link_content_example"));
+  EXPECT_TRUE(ctx.FindLinksByContent("link_content_example").size() == 1);
+
+  EXPECT_TRUE(ctx.EraseElement(linkAddr1));
+
+  EXPECT_TRUE(ctx.FindLinksByContent("link_content_example").empty());
+
+  ctx.Destroy();
```
Comment (KovalM) [inline sc-memory/tests/sc-memory/common/sc-link.cpp:383]:
```suggestion
  ScMemoryContext ctx(sc_access_lvl_make_min, "sc_links_content_changed");

  ScAddr const & linkAddr1 = ctx.CreateLink(ScType::LinkConst);
  EXPECT_TRUE(linkAddr1.IsValid());

  EXPECT_TRUE(ctx.SetLinkContent(linkAddr1, "link_content_example"));
  EXPECT_TRUE(ctx.FindLinksByContent("link_content_example").size() == 1);

  ScAddr const & linkAddr2 = ctx.CreateLink(ScType::LinkConst);
  EXPECT_TRUE(linkAddr2.IsValid());

  EXPECT_TRUE(ctx.SetLinkContent(linkAddr2, "link_content_example"));
  EXPECT_TRUE(ctx.FindLinksByContent("link_content_example").size() == 2);


  EXPECT_TRUE(ctx.EraseElement(linkAddr1));
  EXPECT_TRUE(ctx.FindLinksByContent("link_content_example").size() == 1);

  EXPECT_TRUE(ctx.EraseElement(linkAddr2));
  EXPECT_TRUE(ctx.FindLinksByContent("link_content_example").empty());

  ctx.Destroy();
```

Test with two links is not passed

**Review by KovalM — CHANGES_REQUESTED** [review]

**Review by KovalM — CHANGES_REQUESTED** [review]

**Review by KovalM — APPROVED** [review]
